name: Check Paclet

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  check-paclet:
    name: Check Paclet
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
    timeout-minutes: 10
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Check paclet
        uses: rhennigan/check-paclet@v1.1.0